USE drawings;

DROP TABLE IF EXISTS Users;
CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(50) NOT NULL
);

GRANT ALL PRIVILEGES ON drawings.* TO 'admin'@'%';
FLUSH PRIVILEGES;